BOT_USERNAME = 'ReallyCoolBot'
BOT_PASSWORD = 'password'
CLIENT_ID = 'asdfasdfasdf'
CLIENT_SECRET = 'asdfasdfasdf'
SUBREDDIT = 'SomeSubreddit'
DISCORD_TOKEN = 'asdfasdfasdfY'
DISCORD_GUILD = 'SomeDiscord'
DISCORD_CHANNEL = 'SomeDiscordChannel'
